server:
  port: 8000
resilience4j:
  circuitbreaker:
    configs:
      default:
        minimunNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInopenState: 10s
  retry:
    configs:
      default:
        maxRetryAttempts: 2
        waitDuration: 5
        ignoreException:
          - java.util.NoSuchElementException
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
  bulkhead:
    configs:
      default:
        maxConCurrentCalls: 25
        maxWaitDuration: 0
  ratelimiter:
    configs:
      default:
        limitForPeriod: 50
        limitRefreshPeriod: 500ns
        timeoutDuration: 5s


eureka:
  instance:
    instance-id: inner-gateway-ms-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: inner-gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: study
    password: study12
  cloud:
    gateway:
      routes:
        - id: auth-ms-instance
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}



